### ISSUE TITLE
dicom2nifti fails on Ubuntu 12.04

### ISSUE THREAD

**Issue by lamyj** [lamyj/dicomifier#22]
In `dicomifier.nifti.write`, when extracting `nvox`, the following exception is raised:

```
Traceback (most recent call last):
  File "/home/lamy/src/dicomifier/src/cli/dicom2nifti", line 226, in <module>
    sys.exit(main())
  File "/home/lamy/src/dicomifier/src/cli/dicom2nifti", line 40, in main
    convert(**arguments)
  File "/home/lamy/src/dicomifier/src/cli/dicom2nifti", line 68, in convert
    study_directories, series_directories)
  File "/home/lamy/src/dicomifier/src/cli/dicom2nifti", line 167, in write_nifti
    image, (destination_root + suffix).encode("utf-8"))
TypeError: No registered converter was able to produce a C++ rvalue of type unsigned long from this Python object of type numpy.int64
```

**Comment by lamyj** [comment]
Closed by ffa1dda
